# common
vm:qemu-full,libvirt,virt-manager,virt-viewer,edk2-ovmf,swtpm,libosinfo
dev:neovim,code,dotnet-sdk,nodejs,npm,rustup,opencode,lazygit,python-pynvim,tree-sitter-cli,stylua,shfmt,mono
shell:zsh,tmux,starship,eza,fd,fzf,bat,zoxide,fastfetch
apps:steam,vlc,vlc-plugins-all,wechat-universal-bwrap,feishu-bin,cherry-studio-bin,clash-verge-rev-bin,microsoft-edge-stable-bin,rustdesk-bin,snipaste,todesk-bin,unityhub,w3m,cmatrix,ddgr
multimedia:pipewire,wireplumber,pipewire-pulse,pipewire-alsa,gst-libav,gst-plugins-base,gst-plugins-good,gst-plugins-bad,gst-plugins-ugly
fonts:noto-fonts,noto-fonts-cjk,noto-fonts-emoji,noto-fonts-extra,ttf-jetbrains-mono-nerd
system:base,base-devel,linux,linux-firmware,amd-ucode,networkmanager,openssh,sudo,grub,efibootmgr,sddm,zram-generator,archlinuxcn-keyring,man-db,man-pages,dnsmasq,bluez-utils,power-profiles-daemon,openbsd-netcat,unzip,wl-clipboard,yay
input:fcitx5,fcitx5-configtool,fcitx5-gtk,fcitx5-qt,fcitx5-chinese-addons

# hardware (may not apply to all machines)
nvidia:nvidia-open-dkms,nvidia-utils,lib32-nvidia-utils,nvidia-settings
hardware:asusctl,rog-control-center,keyd
